# Generated by Django 5.0.6 on 2024-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('predicted_label', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Positive'), (2, 'Negative')])),
                ('perceived_label', models.IntegerField(blank=True, choices=[(0, 'Neutral'), (1, 'Positive'), (2, 'Negative')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
